on: push
name: check
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: fetch
        uses: actions/checkout@v3
      - name: install-check # TODO: Cache?
        run: sudo apt-get install -y check
      - name: configure
        run: ./configure
      - name: make check
        run: make check
